name: Deoploy Docusaurus

on:
  workflow_dispatch:
    inputs:
      website_config_file:
        description: 'Website Config'
        required: true
        default: 'website.config.json'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Contents in Repo
        uses: actions/checkout@v2
      - name: Seup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup Project structure
        run: |
          cp ${{ github.event.inputs.website_config_file }} ./website/website.config.json
      - name: Test & Build
        working-directory: ./website
        run: |
          yarn install --frozen-lockfile
          yarn run build
      - name: Create SSH Connection
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        working-directory: ./website
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          yarn install --frozen-lockfile
          yarn run deploy
