name: Convert All of the IPython Notebooks into Markdown
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target File (end with .ipynb)/ Directory'
        required: true
        default: 'AnalysisReport'
      output_dir:
        description: 'Output dir'
        required: true
        default: 'website/docs'
      fig_dir_name:
        description: 'Name of Figure Directory'
        required: true
        default: 'fig'
      website_config_file:
        description: 'Website Config'
        required: true
        default: 'website.config.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Contents in Repo
        uses: actions/checkout@v2
      - name: Setup Ubuntu
        run: |
          sudo apt install jq
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Dependencies in Pipfile
        working-directory: ./mdconverter
        run: |
          pip install --no-cache-dir pipenv
          pipenv install --system --deploy
          pip uninstall -y pipenv virtualenv-clone virtualenv
      - name: Create WebSite Structure
        run: |
          mkdir website/docs
          echo $WEBSITE_TARGET_DIRECTORY
          jq ".target.docs | .[]" $WEBSITE_TARGET_DIRECTORY | xargs -I {} echo {}
          jq ".target.docs | .[]" $WEBSITE_TARGET_DIRECTORY | xargs -I {} cp -r {} website/docs
          tree ./website
      - name: Convert Notebook into Markdown
        run: |
          python mdconverter/convert.py \
            ${{ github.event.inputs.target }} \
            ${{ github.event.inputs.output_dir }} \
            ${{ github.event.inputs.fig_dir_name }}
      - name: Get List
        run: |
          sudo apt install tree
          tree ./website
