name: Convert All of the IPython Notebooks into Markdown
on:
  workflow_dispatch:
    inputs:
      website_config_file:
        description: 'Website Config'
        required: true
        default: 'website.config.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Contents in Repo
        uses: actions/checkout@v2
      - name: Setup Ubuntu
        run: |
          sudo apt install jq
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install Dependencies in Pipfile
        working-directory: ./mdconverter
        run: |
          pip install --no-cache-dir pipenv
          pipenv install --system --deploy
          pip uninstall -y pipenv virtualenv-clone virtualenv
      - name: Create WebSite Structure
        run: |
          mkdir website/docs
          jq ".target.docs | .[]" ${{ github.event.inputs.website_config_file }} \
           | xargs -I {} cp -r {} website/docs
      - name: Convert Notebook into Markdown
        working-directory: ./website/docs
        env:
          TARGET: ./
          OUTPUT_DIR: ./
          FIG_DIR_NAME: fig
        run: |
          python mdconverter/convert.py \
            ${{ env.TARGET }} \
            ${{ env.OUTPUT_DIR }} \
            ${{ env.FIG_DIR_NAME }}
      - name: Remove Unnecessary files (but markdown, gif, jpg, png)
        working-directory: ./website/docs
        run: |
          RUN find . -type f \
          | grep -i -v -E '.*\.(md|jpg|jpeg|png|gif)' \
          | xargs -I {} rm -f {}
      - name: Get List
        run: |
          sudo apt install tree
          tree .
